### ISSUE TITLE
Version 83 crash on launch

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#31]
Hi.

Just got v83.

Seems to crash at license page (ie where you enter your email address for the beta licence).

On Galaxy Tab 10.1

**Comment by fpillet** [comment]
Fixed for next builds, thanks for your feedback (will update the build very soon)

**Comment by rohanvd** [comment]
Hi. Same with v84

**Comment by fpillet** [comment]
Really ? Grrr ok submit those crashes through the notification system, maybe it's a different one! Sorry about that and thanks for your relentless testing

**Comment by rohanvd** [comment]
Hi.

I get to the "Apply for beta license" page at startup but can't enter 
anything. App does not crash out completely. How do I send a log from this 
status ?

RvD

-----Original Message-----

**Comment by rohanvd** [comment]
v86. Still can't enter details on initial license page. Does not appear to have crashed though.
