### ISSUE TITLE
iViewer not connecting to network when WIFI router changed

### ISSUE THREAD

**Issue by geoffbrain** [CommandFusion/iViewer-For-Android#77]
I have a WIFI router in my main back room and a WIFI Extender in the front of the house.  The iCache IR device is connected to the WIFI router in the main room.

If I start iViewer on the router in the main room all works fine.  If I then move to the front of the house and connect to the extender iViewer works but no signals are received by iCache.  

If I stop iViewer in the running apps and restart it the first attempt to restart sees it freeze, hit the home button and get the iViewer crashed message, then restart it and it works including signals being received by iCache.

In other words iViewer seems to somehow be tied to the initial WIFI router it creates a session with.

I tried the opposite (ie Connecting iViewer to the extender then going to the main room router) and the result is the same as described above but all in reverse.

So two bugs
1. iViewer WIFI session issue
2. Restart issue

I have been able to create this problem on Samsung Galaxy S3 and a Bauhn Tablet both running Android V4.0.  This issue does not seem to occur with the browser.

The problem does not seem to occur on my iPad but the on the iPad it take 10 seconds or so  for iViewer to work.

**Comment by geoffbrain** [comment]
Update - if I re-connect to the router that was used when iViewer was first started it resume working.  This seems to confirm that iViewer session is tied to the first router that is uses.

So in summary
- do a force stop of iViewer 
- Start iViewer with WIFI Router router (PC LINK) all works - signals are revceived by iCache
- Change to the extender (netgear UNIVERSAL WIFI RANGE EXTENDER WN3000RP) iViewer appears to work but no signals are received by iCache.
- Change back to the WIFI Router router (PC LINK) all works - signals are revceived by iCache

or visa versa
- do a force stop of iViewer 
- Start iViewer with extender (netgear UNIVERSAL WIFI RANGE EXTENDER WN3000RP) all works - signals are revceived by iCache
- Change to the WIFI Router router (PC LINK) iViewer appears to work but no signals are received by iCache.
- Change back to the extender (netgear UNIVERSAL WIFI RANGE EXTENDER WN3000RP) all works - signals are revceived by iCache

I hope this is clearer

**Comment by fpillet** [comment]
So, to summarize: when you switch WIFI networks, you lose connectivity to the external systems defined in your GUI, and connecting back to the original network restores connectivity? Thanks a lot for this detailed information!

**Comment by geoffbrain** [comment]
Your one line summary is correct.  One additional clarification if force stop iViewer and restart if it works fine on the network that the device is now using.

**Comment by fpillet** [comment]
Fixed for next build - thanks a lot for the report!

**Comment by geoffbrain** [comment]
Test results using build 105

I have two wifi routers
Router 1. Main Netgear WIFI Cable router CG3100D  (in main room)
Router 2. Netgear WIFI extender WN3000RP (in study - 25 meters away)

Router 2 connects to router 1 to extend the range

Using Samsung S3 Android 4.1 iViewer 105 iCache GC-100-12 (fixed IP address).  Each scenario assumes a clean start of IViewer - that is I do a force stop and then start iViewer.

Scenario A. If I connect to Router 1. all works fine and even my iPad works fine in combination with the Android device

Scenario B. If I connect to Router 2. all works fine and even my iPad works fine in combination with the Android device

Scenario C. If I connect to Router 1. all works fine.  If I then connect to Router 2. no signals get through  If I reconnect to Router 1. no signals get through.  I have to do a force stop of iViewer to fix the problem.

Scenario D. If I connect to Router 2. all works fine.  If I then connect to Router 1. no signals get through.  If I reconnect to Router 2. no signals get through.  I have to do a force stop of iViewer to fix the problem.

Scenario C. did work once or twice (no predictable) but scenario D always does not work.

In all cases there does not appear to be any issue with the iPad working.

I no longer get any crashes of iViewer when restarting after a force stop - this use to occur.

**Comment by geoffbrain** [comment]
I did some more playing around and found that I can get iViewer to work when switching WIFI routers by exiting the iViewer application. (ie. I do not have to a force stop).  By pressing the return button.

If I switch to the main screen by pressing the home button (ie iViewer is still running in background) then the problem persists.

**Comment by fpillet** [comment]
Great feedback, thanks a lot Geoff. We're looking into it - new build soon.

**Comment by fpillet** [comment]
Update on this issue - there seem to be a general network-switching issue, as running tests on a phone exhibits issues during switching from 3G to WiFi. We're working on it.

**Comment by fpillet** [comment]
Can you please try with the just-release build 122? A number of issues related to network switches have been fixed. I don't promise that yours has been, but I think that this release is worth testing.

**Comment by geoffbrain** [comment]
OK with Beta 122 I can report that so far I have had no network issues
1. Ipad and Android do not seem to interfere with each other in any way
2. Switching between two WIFI routers on my home network now seems to work without any issues.

The only issue I now see if if I do a Stop of iViewer (in the Application management of the Android) and then restart it the loading screen come up with the iViewer logo and nothing happens (there is no preparing GUI message) .  If I exit iViewer and then restart it (no stop action) or try reloading the GUI iViewer crashes and bug report is sent to you.  If I then restart iViewer all works fine - the loading screen come up with the iViewer logo and a little box saying preparing GUI and all works.

The GUI assets and layouts also seem to load with less missing assets.  However I do get the odd iViewer crash during the process, nothing I can repeats in a consistent manner.

**Comment by fpillet** [comment]
Should be working fine now with just-release build 131. Please create new bugs if you have other (unrelated) issues
